version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: gamer_machine_db
    environment:
      POSTGRES_USER: gamer
      POSTGRES_PASSWORD: gamer
      POSTGRES_DB: gamer_machine
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gamer -d gamer_machine']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
